spring.application.name=BookingSystem
server.port=8200

# Database config
spring.datasource.url=jdbc:mysql://localhost:3306/booking_sy
spring.datasource.username=root
spring.datasource.password=u_s057385EEEE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html